### ISSUE TITLE
How to make the URL appear in helm description

### ISSUE THREAD

**Issue by thierryvolpiatto** [milkypostman/melpa#2594]
I have already added an `:url` entry in helm-pkg.el, but it seems it is not enough.

Thanks.

**Comment by purcell** [comment]
Which description are you referring to?

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Which description are you referring to?

HOME: http://github.com/emacs-helm/helm

I would like to see this entry in package description.
Here what I have actually:

helm is an available package.

     Status: Available from melpa -- Install
    Archive: melpa
    Version: 20150313.1353
   Requires: emacs-24, cl-lib-0.5, async-1.2
    Summary: Helm is an Emacs incremental and narrowing framework


Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I meant:
Homepage: http....

Sorry.

**Comment by purcell** [comment]
Great, thanks -- I see what you mean now. There's no `:url` property in the package descriptor we write. I'll investigate.

**Comment by purcell** [comment]
Done in e9bce98, I believe.

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> Done in e9bce98, I believe.

Hmm, still the same.
Maybe it is me who do something wrong ? But what ?
I see that slime that have multiple files like helm, have the url
displayed in its description, don't know why though.
It have the same flag ":url" in its *-pkg.el file.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
No, I tested it locally with helm. Perhaps the package just hasn’t rebuilt yet. I’ll take a look tomorrow.

-Steve

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> No, I tested it locally with helm. Perhaps the package just hasn’t rebuilt yet. I’ll take a look tomorrow.

Ah, ok sorry, will wait tomorrow.
Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
Looks like I also messed something up: fdc6654

In any case, I hope the next build cycle will fix things.

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

> No, I tested it locally with helm. Perhaps the package just hasn’t rebuilt yet. I’ll take a look tomorrow.

It is working perfectly now, the Homepage entry is now appearing :-)

Many thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by purcell** [comment]
Yay, great! Thanks for filing this issue.
